name: Caller flow
run-name: I am the caller
on: 
    workflow_dispatch: 
        inputs:
            osname:
                type: string
                required: true
                description: enter os name
jobs:
    firstjob:
        name: My first job
        uses: ./.github/workflows/callee.yml
        with:
            osname: ${{ inputs.osname }}
        secrets: 
            username: pradeep shetty
    secondjob:
        needs: firstjob
        runs-on: ${{ inputs.osname }}
        steps:
            - name: hello how are you
              run: |
                echo "data value is ${{ needs.firstjob.outputs.somedata }}"
              
        
            
