name: Testing my workflow
run-name: New Workflow
on: 
  workflow_dispatch:
    inputs:
      osname: 
        description: Enter os name
        required: true
        type: string
      runNumber:
        description: enter run number
        required: true
        type: number      
jobs:
    firstjob:
        name: My first job
        strategy:
            matrix:
                node_version: [A, B, C]
                os_version: [1,2]
                include:
                    - node_version: D
                      os_version: 3
                    - node_version: E
                      os_version: 4
                exclude:
                    - node_version: B
                      os_version: 2
                    - node_version: C
                      os_version: 1
                
        runs-on: ubuntu-latest
        steps:
            - name: First Step
              run: |
                echo "Values are ${{ matrix.node_version }} ---> ${{ matrix.os_version }}"
    secondjob:
        name: second job
        uses: ./.github/workflows/callableflow.yml
        with:
          osname: ${{ inputs.osname }}
          runNumber: ${{ inputs.runNumber }}

        
        

          

        

